package database

import (
	_ "embed"
	"fmt"
	"strings"

	"gorm.io/gorm"
)

//go:embed schema.sql
var schemaSQL string

// Migrate 幂等执行建表语句（按 ; 切分，剔除注释行后逐条执行）。
// schema.sql 以 SQLite 方言书写；postgres 模式在执行前做模板替换：
//   INTEGER PRIMARY KEY AUTOINCREMENT → BIGINT GENERATED BY DEFAULT AS IDENTITY
//   （BY DEFAULT 允许显式插 id，供 -migrate-from-sqlite 搬数据）
//   INTEGER → BIGINT（额度/成本可能超出 int4）
//   PRAGMA 语句跳过（PG 外键约束默认即时生效）
func Migrate(db *gorm.DB) error {
	for _, stmt := range splitStatements(schemaSQL) {
		if Dialect == "postgres" {
			if strings.HasPrefix(strings.ToUpper(stmt), "PRAGMA") {
				continue
			}
			stmt = strings.ReplaceAll(stmt, "INTEGER PRIMARY KEY AUTOINCREMENT",
				"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
			stmt = strings.ReplaceAll(stmt, " INTEGER", " BIGINT")
		}
		if err := db.Exec(stmt).Error; err != nil {
			return fmt.Errorf("migrate %q: %w", truncate(stmt, 60), err)
		}
	}
	// 已有库的幂等加列（CREATE TABLE IF NOT EXISTS 不会更新旧表结构）
	alters := [][3]string{
		{"users", "email", "TEXT NOT NULL DEFAULT ''"},
		{"models", "cost_input_price", "INTEGER NOT NULL DEFAULT 0"},
		{"models", "cost_output_price", "INTEGER NOT NULL DEFAULT 0"},
		{"usage_logs", "cost_input_price", "INTEGER NOT NULL DEFAULT 0"},
		{"usage_logs", "cost_output_price", "INTEGER NOT NULL DEFAULT 0"},
		{"usage_logs", "vendor_cost", "INTEGER NOT NULL DEFAULT 0"},
		{"usage_logs", "cache_hit", "INTEGER NOT NULL DEFAULT 0"},
		{"orgs", "require_cost_center", "INTEGER NOT NULL DEFAULT 0"},
		{"api_keys", "cost_center_id", "INTEGER"},
		{"usage_logs", "cost_center_id", "INTEGER"},
		{"orgs", "alert_levels", "TEXT NOT NULL DEFAULT '[80]'"},
		{"orgs", "alert_level", "INTEGER NOT NULL DEFAULT 0"},
		{"orgs", "alert_since", "INTEGER NOT NULL DEFAULT 0"},
		{"users", "alert_levels", "TEXT NOT NULL DEFAULT '[80]'"},
		{"users", "alert_level", "INTEGER NOT NULL DEFAULT 0"},
		{"users", "alert_since", "INTEGER NOT NULL DEFAULT 0"},
	}
	for _, a := range alters {
		if !columnExists(db, a[0], a[1]) {
			if err := db.Exec(fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s", a[0], a[1], a[2])).Error; err != nil {
				return fmt.Errorf("alter %s.%s: %w", a[0], a[1], err)
			}
		}
	}
	return nil
}

// columnExists 方言分支：sqlite 用 pragma_table_info，postgres 用 information_schema
func columnExists(db *gorm.DB, table, column string) bool {
	var cnt int64
	if Dialect == "postgres" {
		_ = db.Raw(`SELECT COUNT(*) FROM information_schema.columns
			WHERE table_name = ? AND column_name = ?`, table, column).Scan(&cnt).Error
	} else {
		_ = db.Raw("SELECT COUNT(*) FROM pragma_table_info(?) WHERE name = ?", table, column).Scan(&cnt).Error
	}
	return cnt > 0
}

func splitStatements(sql string) []string {
	var stmts []string
	for _, part := range strings.Split(sql, ";") {
		var lines []string
		for _, line := range strings.Split(part, "\n") {
			if t := strings.TrimSpace(line); strings.HasPrefix(t, "--") {
				continue
			}
			lines = append(lines, line)
		}
		if st := strings.TrimSpace(strings.Join(lines, "\n")); st != "" {
			stmts = append(stmts, st)
		}
	}
	return stmts
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
